export type Recipe = {
  id: string;
  title: string;
  description: string;
  image: string;
  prepTime: string
  cookTime: string
  servings: number
  ingredients: string[]
  instructions: string[]
  category: string
}

export const recipes: Recipe[] = [
    {
    id: "1",
    title: "Brownie",
    description: "Um delicioso e clássico brownie ,com uma casquinha crocante e perfeito para os amantes de chocolate",
    image: "/receitas/brownie.png",
    prepTime: "10 minutos",
    cookTime: "20 minutos",
    servings: 1,
    ingredients: [
      "170g manteiga sem sal",
      "120g chocolate 70%",
      "200g de açucar",
      "3 ovos",
      "40g de cacau em pó",
      "60g de farinha de trigo",
      "Essência de baunilha",
      "160g de chocolate ao leite"
    ],
    instructions: [
      "Derreta a manteiga e o chocolate 70%",
      "Em uma batedeira, misture os ovos e o açucar até ficarem homogêneos",
      "Em uma tigela, junte a mistura de ovos e açúcar com a manteiga e o chocolate derretidos",
      "Depois, entre com os ingredientes secos",
      "Finalize com essencia de baunilha e chocolate ao leite em pedaços",
      "Leve ao forno por 20 minutos",
    ],
    category: "Sobremesas",
  },
  {
    id: "2",
    title: "Carbonara",
    description: "Um clássico da culinária romana, este Carbonara é cremoso, saboroso e feito com poucos ingredientes, mas de alta qualidade.",
    image: "/receitas/carbonara.jpeg",
    prepTime: "15 minutos",
    cookTime: "20 minutos",
    servings: 2,
    ingredients: [
      "200g de massa (spaghetti ou rigatoni )",
      "150g de guanciale (ou pancetta)",
      "2 gemas de ovo grandes",
      "50g de queijo Pecorino ralado",
      "Pimenta do reino moída na hora a gosto",
    ],
    instructions: [
      "Cozinhe a massa em água fervente com sal até ficar al dente. Reserve uma concha da água do cozimento.",
      "Enquanto a massa cozinha, corte o guanciale (ou pancetta) em cubos pequenos.",
      "Em uma frigideira grande, cozinhe o guanciale em fogo médio até ficar crocante e dourado. Não adicione óleo, a gordura do guanciale será suficiente. Retire o guanciale da frigideira e reserve, deixando a gordura na frigideira.",
      "Em uma tigela separada, misture as gemas de ovo com o Pecorino Romano ralado e uma boa quantidade de pimenta do reino moída na hora. Adicione 1-2 colheres de sopa da água do cozimento da massa para criar um creme homogêneo.",
      "Escorra a massa e adicione-a diretamente à frigideira com a gordura do guanciale. Mexa bem para cobrir a massa com a gordura.",
      "Fora do fogo (ou com o fogo bem baixo para não cozinhar os ovos), adicione a mistura de ovos e queijo à massa. Mexa vigorosamente e rapidamente para emulsionar e criar um molho cremoso. Se a massa parecer muito seca, adicione mais um pouco da água do cozimento reservada.",
      "Adicione o guanciale crocante de volta à massa e misture bem.",
      "Sirva imediatamente, finalizando com mais pimenta do reino moída na hora e, se desejar, um pouco mais de Pecorino Romano ralado.",
    ],
    category: "Pratos Principais",
  },
  {
    id: "3",
    title: "Salada Caprese",
    description: "Uma salada italiana clássica com tomate, mussarela de búfala e manjericão fresco.",
    image: "/receitas/salada-caprese.png",
    prepTime: "10 minutos",
    cookTime: "0 minutos",
    servings: 2,
    ingredients: [
      "2 tomates maduros grandes",
      "200g de mussarela de búfala",
      "Folhas de manjericão fresco",
      "2 colheres de sopa de azeite de oliva extra virgem",
      "1 colher de sopa de vinagre balsâmico",
      "Sal e pimenta a gosto",
    ],
    instructions: [
      "Corte os tomates e a mussarela em fatias de aproximadamente 1 cm de espessura.",
      "Em um prato, alterne as fatias de tomate e mussarela.",
      "Distribua as folhas de manjericão por cima.",
      "Regue com azeite de oliva e vinagre balsâmico.",
      "Tempere com sal e pimenta a gosto.",
      "Sirva imediatamente.",
    ],
    category: "Entradas",
  },
    {
    id: "4",
    title: "Bolo de Chocolate",
    description: "Um delicioso bolo de chocolate fofinho e úmido, perfeito para qualquer ocasião.",
    image: "/receitas/bolo-chocolate.jpg",
    prepTime: "15 minutos",
    cookTime: "35 minutos",
    servings: 8,
    ingredients: [
      "2 xícaras de farinha de trigo",
      "2 xícaras de açúcar",
      "3/4 xícara de cacau em pó",
      "2 colheres de chá de fermento em pó",
      "1 colher de chá de bicarbonato de sódio",
      "1 colher de chá de sal",
      "2 ovos",
      "1 xícara de leite",
      "1/2 xícara de óleo vegetal",
      "2 colheres de chá de essência de baunilha",
      "1 xícara de água quente",
    ],
    instructions: [
      "Pré-aqueça o forno a 180°C e unte uma forma redonda.",
      "Em uma tigela grande, misture os ingredientes secos: farinha, açúcar, cacau, fermento, bicarbonato e sal.",
      "Adicione os ovos, leite, óleo e baunilha. Bata com um batedor de arame por cerca de 2 minutos.",
      "Adicione a água quente à massa. A massa ficará bem líquida, mas é normal.",
      "Despeje a massa na forma preparada.",
      "Asse por 30-35 minutos, ou até que um palito inserido no centro saia limpo.",
      "Deixe esfriar por 10 minutos antes de desenformar.",
    ],
    category: "Sobremesas",
  },
    {
    id: "5",
    title: "Risoto de Cogumelos",
    description: "Um risoto cremoso com cogumelos frescos e parmesão, perfeito para um jantar especial.",
    image: "/receitas/risoto-cogumelos.jpeg",
    prepTime: "10 minutos",
    cookTime: "30 minutos",
    servings: 4,
    ingredients: [
      "1 1/2 xícara de arroz arbóreo",
      "400g de cogumelos variados",
      "1 cebola média picada",
      "2 dentes de alho picados",
      "1/2 xícara de vinho branco seco",
      "4 xícaras de caldo de legumes quente",
      "1/2 xícara de queijo parmesão ralado",
      "2 colheres de sopa de manteiga",
      "2 colheres de sopa de azeite de oliva",
      "Sal e pimenta a gosto",
      "Salsinha picada para finalizar",
    ],
    instructions: [
      "Em uma panela grande, aqueça o azeite e 1 colher de manteiga em fogo médio.",
      "Adicione a cebola e refogue até ficar transparente, cerca de 3 minutos.",
      "Adicione o alho e refogue por mais 1 minuto.",
      "Adicione os cogumelos e cozinhe até que estejam macios e dourados.",
      "Adicione o arroz e mexa por 1-2 minutos até que fique levemente translúcido.",
      "Despeje o vinho branco e mexa até que seja absorvido.",
      "Adicione o caldo de legumes, uma concha por vez, mexendo frequentemente e esperando que o líquido seja absorvido antes de adicionar mais.",
      "Quando o arroz estiver al dente (cerca de 18-20 minutos), retire do fogo.",
      "Adicione o queijo parmesão e a manteiga restante, mexendo até incorporar.",
      "Tempere com sal e pimenta a gosto e finalize com salsinha picada.",
    ],
    category: "Pratos Principais",
  },
]